export const LEVELS = [
  {
    id: 1,
    name: 'Livello 1',
    // Griglia obiettivo, non garantita: definisce solo il tetto di coppie
    // (columns * rows / 2). Se le basi selezionate non forniscono abbastanza
    // valori utilizzabili, il numero effettivo di tessere si riduce e il
    // layout mostrato viene ricalcolato da findBoardGrid, non letto da qui.
    grid: { columns: 4, rows: 4 },
    valueRange: { min: 0, max: 15 },
    timeLimitSeconds: 180,
    coveredRatio: 0,
    requireDecimalPivot: true,
  },
  {
    id: 2,
    name: 'Livello 2',
    grid: { columns: 4, rows: 4 },
    valueRange: { min: 0, max: 31 },
    timeLimitSeconds: 180,
    coveredRatio: 0,
    requireDecimalPivot: true,
  },
  {
    id: 3,
    name: 'Livello 3',
    grid: { columns: 4, rows: 4 },
    valueRange: { min: 0, max: 31 },
    timeLimitSeconds: 120,
    coveredRatio: 0,
    requireDecimalPivot: true,
  },
  {
    id: 4,
    name: 'Livello 4',
    grid: { columns: 5, rows: 4 },
    valueRange: { min: 0, max: 31 },
    timeLimitSeconds: 120,
    coveredRatio: 0,
    requireDecimalPivot: true,
  },
  {
    id: 5,
    name: 'Livello 5',
    grid: { columns: 5, rows: 4 },
    valueRange: { min: 0, max: 63 },
    timeLimitSeconds: 120,
    coveredRatio: 0,
    requireDecimalPivot: true,
  },
  {
    id: 6,
    name: 'Livello 6',
    grid: { columns: 6, rows: 4 },
    valueRange: { min: 0, max: 63 },
    timeLimitSeconds: 120,
    coveredRatio: 0,
    requireDecimalPivot: true,
  },
  {
    id: 7,
    name: 'Livello 7',
    grid: { columns: 6, rows: 4 },
    valueRange: { min: 0, max: 63 },
    timeLimitSeconds: 90,
    coveredRatio: 0,
    requireDecimalPivot: true,
  },
  {
    id: 8,
    name: 'Livello 8',
    grid: { columns: 6, rows: 4 },
    valueRange: { min: 0, max: 63 },
    timeLimitSeconds: 90,
    coveredRatio: 0,
    requireDecimalPivot: false,
  },
  {
    id: 9,
    name: 'Livello 9',
    grid: { columns: 6, rows: 5 },
    valueRange: { min: 0, max: 63 },
    timeLimitSeconds: 90,
    coveredRatio: 0,
    requireDecimalPivot: false,
  },
  {
    id: 10,
    name: 'Livello 10',
    grid: { columns: 6, rows: 6 },
    valueRange: { min: 0, max: 63 },
    timeLimitSeconds: 90,
    coveredRatio: 0,
    requireDecimalPivot: false,
  },
  {
    id: 11,
    name: 'Livello 11',
    grid: { columns: 6, rows: 6 },
    valueRange: { min: 0, max: 127 },
    timeLimitSeconds: 90,
    coveredRatio: 0,
    requireDecimalPivot: false,
  },
  {
    id: 12,
    name: 'Livello 12',
    grid: { columns: 6, rows: 6 },
    valueRange: { min: 0, max: 127 },
    timeLimitSeconds: 90,
    coveredRatio: 0.1,
    requireDecimalPivot: false,
  },
  {
    id: 13,
    name: 'Livello 13',
    grid: { columns: 6, rows: 6 },
    valueRange: { min: 0, max: 127 },
    timeLimitSeconds: 90,
    coveredRatio: 0.3,
    requireDecimalPivot: false,
  },
  {
    id: 14,
    name: 'Livello 14',
    grid: { columns: 6, rows: 6 },
    valueRange: { min: 0, max: 127 },
    timeLimitSeconds: 90,
    coveredRatio: 0.5,
    requireDecimalPivot: false,
  },
  {
    id: 15,
    name: 'Livello 15',
    grid: { columns: 6, rows: 6 },
    valueRange: { min: 0, max: 127 },
    timeLimitSeconds: 90,
    coveredRatio: 1,
    requireDecimalPivot: false,
  },
];

export function getLevelById(id) {
  return LEVELS.find((level) => level.id === id);
}
